//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditLog
    {
        public System.Guid LogID { get; set; }
        public Nullable<System.Guid> AuditConfigId { get; set; }
        public string EntityName { get; set; }
        public string FieldName { get; set; }
        public string OldValue { get; set; }
        public string OldvalueDesc { get; set; }
        public string NewValue { get; set; }
        public string NewValueDesc { get; set; }
        public System.Guid UserId { get; set; }
        public System.Guid PatientId { get; set; }
        public System.DateTime ChangeDate { get; set; }
        public string TransactionType { get; set; }
    
        public virtual Mast_AuditSchema Mast_AuditSchema { get; set; }
    }
}
