//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogEntity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AuditLogDbEntities : DbContext
    {
        public AuditLogDbEntities()
            : base("name=AuditLogDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Allergy> Allergies { get; set; }
        public virtual DbSet<AuditLog> AuditLogs { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Gender> Genders { get; set; }
        public virtual DbSet<Mast_AuditSchema> Mast_AuditSchema { get; set; }
        public virtual DbSet<PAddress> PAddresses { get; set; }
        public virtual DbSet<Patient> Patients { get; set; }
        public virtual DbSet<PatientInfo> PatientInfoes { get; set; }
    }
}
