//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mast_AuditSchema
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mast_AuditSchema()
        {
            this.AuditLogs = new HashSet<AuditLog>();
        }
    
        public System.Guid ConfigId { get; set; }
        public Nullable<System.Guid> PracticeID { get; set; }
        public string ParentEntity { get; set; }
        public string Entity { get; set; }
        public string AttributeName { get; set; }
        public bool IsAuditable { get; set; }
        public bool IsLookup { get; set; }
        public string LookupTable { get; set; }
        public string LookupId { get; set; }
        public string LookupDescription { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AuditLog> AuditLogs { get; set; }
    }
}
