//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientInfo
    {
        public System.Guid PatientInfoId { get; set; }
        public string PatientName { get; set; }
        public string PatientAge { get; set; }
        public string PatientContactNo { get; set; }
        public Nullable<System.Guid> PatientAddress { get; set; }
        public Nullable<System.Guid> PatientGender { get; set; }
    
        public virtual Gender Gender { get; set; }
        public virtual PAddress PAddress { get; set; }
    }
}
